"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import spa_gui

# Implementing MyFrame1
class spa_guiMyFrame1( spa_gui.MyFrame1 ):
	def __init__( self, parent ):
		spa_gui.MyFrame1.__init__( self, parent )

	# Handlers for MyFrame1 events.
	def onButtonClickBrouseInputFileName( self, event ):
		# TODO: Implement onButtonClickBrouseInputFileName
		pass

	def onButtonClickExecute( self, event ):
		# TODO: Implement onButtonClickExecute
		pass


