"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import spa_gui_builder

# Implementing MyFrame1
class spa_gui_builderMyFrame1( spa_gui_builder.MyFrame1 ):
	def __init__( self, parent ):
		spa_gui_builder.MyFrame1.__init__( self, parent )

	# Handlers for MyFrame1 events.
	def onButtonClickBrouseInputFileName( self, event ):
		# TODO: Implement onButtonClickBrouseInputFileName
		pass

	def OnComboboxWindowType( self, event ):
		# TODO: Implement OnComboboxWindowType
		pass

	def OnTextRbwBandwidth( self, event ):
		# TODO: Implement OnTextRbwBandwidth
		pass

	def onButtonClickExecute( self, event ):
		# TODO: Implement onButtonClickExecute
		pass


